apiVersion: v2
name: opa-exporter
description: Helm chart for opa-exporter, a prometheus exporter for OPA Gatekeeper.
type: application
version: 0.1.2
appVersion: 0.2.0
home: https://github.com/csullivanupgrade/opa-exporter
