# -- opa-exporter configuration
exporter:
  # -- whether the exporter is running inside the cluster (i.e. use a service account)
  inCluster: true
  # -- constraints API scrape interval
  interval: "60s"
  # -- log level to use, uses Zap levels
  logLevel: info
  # -- log mode to use:
  # ---- `development` adds extra stacktrace/codepath fields
  # ---- `nop` disables the logger
  logMode: production
  # -- path for metrics server to listen
  path: "metrics"
  # -- port for the server to listen
  port: "9141"

# -- Count of Pod replicas
replicaCount: 1

# Image configuration for the Agent container
image:
  # -- Image repository and name
  repository: ghcr.io/csullivanupgrade/opa-exporter
  # -- Overrides the image tag whose default is the chart `appVersion`
  tag: ""
  # -- List of image pull secrets
  pullSecrets: []
  # -- imagePullPolicy, default value will not add the field
  pullPolicy: ""

# -- namespace the exporter should run in
namespace: opa-exporter

# Creation of the Service Account used by the Pod
serviceAccount:
  # -- Whether to enable the Service Account used by the Pod
  enabled: true
  # -- If not set and `enabled` is `true`, a name is generated using the fullname template
  name: ""
  # -- Annotations to add to the service account
  annotations: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod security context
podSecurityContext: {}

# -- Security context for the Agent container
securityContext: {}
# securityContext:
#   capabilities:
#     drop:
#       - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: "9141"

serviceMonitor:
  # -- Wherter to install `ServiceMonitor` or not
  enabled: false
  # -- Extra labels
  extraLabels: {}

# -- Resources for the Agent container
resources: {}

# -- Pod node selector
nodeSelector: {}

# -- Pod tolerations
tolerations: []

# -- Pod affinity
affinity: {}

rbac:
  # -- Whether to enable Cluster Role and Cluster Role Binding
  enabled: true
  # -- (string) Use an existing ClusterRole/Role
  useExistingRole:
  # -- Extra ClusterRole rules
  extraClusterRoleRules: []
  # extraClusterRoleRules:
  #   - apiGroups: []
  #     resources: []
  #     verbs: []
